package org.codeart.saga.model;

/**
 * SAGA execution status.
 */
public enum SagaStatus {
    STARTED,
    PAYMENT_PENDING,
    PAYMENT_COMPLETED,
    PAYMENT_FAILED,
    INVENTORY_PENDING,
    INVENTORY_RESERVED,
    INVENTORY_FAILED,
    SHIPPING_PENDING,
    SHIPPING_SCHEDULED,
    SHIPPING_FAILED,
    COMPLETED,
    COMPENSATING,
    COMPENSATED,
    FAILED
}
